unclassified:
  globalNexusConfiguration:
    nxrmConfigs:
    - nxrm3Configuration:
        credentialsId: "nexus3_cred"
        displayName: "Nexus3"
        id: "Nexus3"
        internalId: "0e3b990c-c45c-4672-8329-abf3ea5746a0"
        serverUrl: "http://nexus..com"
